### ISSUE TITLE
bug in profile

### ISSUE THREAD

**Issue by taulpotsol** [steveEECSrubin/angular_project#7]
При  открытии профиля и его редактировании периодически двоит верхняя картинка как на принтскрине
![2018-01-30_12-43-19](https://user-images.githubusercontent.com/35600126/35636901-a117a854-06c3-11e8-86ab-1a26cb6f2183.png)

**Comment by vtsybulin** [comment]
![screen shot 2018-02-02 at 5 15 52 pm](https://user-images.githubusercontent.com/25992258/35740236-d3e41108-083c-11e8-9f6a-e3008d0d5429.png)

вот эта же кнопка?

**Comment by taulpotsol** [comment]
да эта.
